# -*- coding: utf-8 -*-
"""DSProject_IT_Salary_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G0UYm0HxcFg2QYXOAKbuz3hRfpODrN_h

# Importing basic libraries
"""

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Salary_Dataset_with_Extra_Features.csv')

# getting first five rows of dataset
df.head()

df.shape

df.info()

df.describe()

df.columns

# which company has maximum number of employess 

df['Company Name'].value_counts()

# maximum employees works as which job title
df['Job Title'].value_counts()

df['Job Title'].unique()

# maximum employees works in which location
df['Location'].value_counts()

df['Job Roles'].value_counts()

# distribution of employees on the basis of employment type 

df['Employment Status'].value_counts()

#finding and dropping null values
df.isnull()



"""# Visualizing insights of Features"""

# checking distribution of rating feature
plt.figure(figsize=(10,5))
sns.distplot(df['Rating'])

plt.figure(figsize=(15,5))
sns.countplot(df['Job Roles'])

plt.figure(figsize=(15,5))
sns.countplot(df['Job Roles'],hue=df['Employment Status'])

plt.figure(figsize=(15,5))
sns.countplot(df['Location'])

plt.figure(figsize=(15,5))
sns.countplot(df['Location'],hue=df['Employment Status'])

sns.countplot(df['Employment Status'])

"""**People are more interested in getting Full time job as compared to intern , contrater and trainee.**"""

sns.distplot(df['Salary'])

df['Salaries Reported'].value_counts()

df.drop('Salaries Reported',axis=1,inplace=True)

df.columns

# Top 20 companies with 5.0 ratings.

df[['Company Name','Rating']].sort_values('Rating',ascending=False).head(20)

highest_salary_job = df.nlargest(5,['Salary'])
highest_salary_job

sns.pairplot(df)

plt.figure(figsize=(20,8))
sns.barplot(data=df,x='Location',y='Salary',hue=df['Employment Status'])

plt.figure(figsize=(15,5))
sns.barplot(data=df,x='Location',y='Salary')

plt.figure(figsize=(20,7))
sns.barplot(data=df,x='Job Roles',y='Salary')

"""**Instead maximum people work as SDE but they can't pay much by companies. We can see Database job role payed more rather than other job roles.**

#
"""